### ISSUE TITLE
Make a good README file

### ISSUE THREAD

**Issue by Susmita-Dey** [opensourcecommunity-hub/amazing-github-projects-collection#4]
The README file should be customized.

**Comment by Susmita-Dey** [comment]
I want to have the readme some contributing guidelines like steps how they can add their projects and project ideas to this repo.

**Comment by AryanGodara** [comment]
> I want to have the readme some contributing guidelines like steps how they can add their projects and project ideas to this repo.

So, people just have to paste the 'link' of the GitHub repo, that they want to add to the 'projects.md' right?
I can write the steps for that in the README.md
Can you please tell what kind of contributing.md file you want? Like  some examples, and the guidelines that you want.
Then, I'll starting writing these two files

**Comment by Susmita-Dey** [comment]
Yes, you're right. 
The **contributing.md file** must contain the guidelines for a beginner like how to fork a repo, then make changes and create a **Pull request**
Also add the discord community link if they face any issue while contributing.
**_You can find the discord community link in the community profile._**

> Kindly join the discord community if you face any issue and you can also raise an issue to be the member of this community.

**Comment by AryanGodara** [comment]
> Yes, you're right. 
> The **contributing.md file** must contain the guidelines for a beginner like how to fork a repo, then make changes and create a **Pull request**
> Also add the discord community link if they face any issue while contributing.
> **_You can find the discord community link in the community profile._**
> 
> > Kindly join the discord community if you face any issue and you can also raise an issue to be the member of this community.

Alright, I've understood now.
can I take 1-2 days to complete this? As I also have to manage my college classes.
i will get it done as soon as possible.
thanks!

**Comment by Susmita-Dey** [comment]
No problem. Take your time ☺️

**Comment by Susmita-Dey** [comment]
> > Yes, you're right.
> > The **contributing.md file** must contain the guidelines for a beginner like how to fork a repo, then make changes and create a **Pull request**
> > Also add the discord community link if they face any issue while contributing.
> > **_You can find the discord community link in the community profile._**
> > > Kindly join the discord community if you face any issue and you can also raise an issue to be the member of this community.
> 
> Alright, I've understood now. can I take 1-2 days to complete this? As I also have to manage my college classes. i will get it done as soon as possible. thanks!

Are you still working on this issue?

**Comment by AryanGodara** [comment]
> > > Yes, you're right.
> > > The **contributing.md file** must contain the guidelines for a beginner like how to fork a repo, then make changes and create a **Pull request**
> > > Also add the discord community link if they face any issue while contributing.
> > > **_You can find the discord community link in the community profile._**
> > > > Kindly join the discord community if you face any issue and you can also raise an issue to be the member of this community.
> > 
> > Alright, I've understood now. can I take 1-2 days to complete this? As I also have to manage my college classes. i will get it done as soon as possible. thanks!
> 
> Are you still working on this issue?

yes, I added a contributing.md file yesterday.
it seems like I forgot to create a proper pull request.
give me 5 minutes

**Comment by Susmita-Dey** [comment]
> > > > Yes, you're right.
> > > > The **contributing.md file** must contain the guidelines for a beginner like how to fork a repo, then make changes and create a **Pull request**
> > > > Also add the discord community link if they face any issue while contributing.
> > > > **_You can find the discord community link in the community profile._**
> > > > > Kindly join the discord community if you face any issue and you can also raise an issue to be the member of this community.
> > > 
> > > 
> > > Alright, I've understood now. can I take 1-2 days to complete this? As I also have to manage my college classes. i will get it done as soon as possible. thanks!
> > 
> > 
> > Are you still working on this issue?
> 
> yes, I added a contributing.md file yesterday. it seems like I forgot to create a proper pull request. give me 5 minutes

Okay

**Comment by AryanGodara** [comment]
Please check the file now. I'm sorry for my mistake. I added the file to the forked repository somehow, and not to this original one.

**Comment by Susmita-Dey** [comment]
Okay, checking.
